apiVersion: apps/v1
kind: Deployment
metadata:
  name: workprofile-deployment
  labels:
    app: workprofile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workprofile
  template:
    metadata:
      labels:
        app: workprofile
    spec:
      containers:
      - name: workprofile
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
