apiVersion: v1
kind: Service
metadata:
  name: workprofile-service
spec:
  type: NodePort
  selector:
    app: workprofile
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    # nodePort: 30080  # אפשר לבחור או לא להגדיר ולתת Kubernetes לבחור
