name: WorkProfile CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t workprofile:test .

      - name: Run container
        run: docker run -d -p 5000:5000 --name test_container workprofile:test

      - name: Wait for app to start
        run: sleep 5

      - name: Test root endpoint
        run: curl --fail http://localhost:5000/

      - name: Test health endpoint
        run: curl --fail http://localhost:5000/health

      - name: Stop and remove container
        run: docker rm -f test_container

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image with Docker Hub tag
        run: docker build -t tehilaalkoby/workprofile:latest .

      - name: Push image to Docker Hub
        run: docker push tehilaalkoby/workprofile:latest
